### ISSUE TITLE
Plans to create new commands (open and close)?

### ISSUE THREAD

**Issue by tim-massey** [schacon/git-pulls#52]
Does anyone have plans to extend this to have commands to open and close pull requests? If not, I'll send a PR.

To create a pull from the current branch:
`git pull open -t <title> -d <description>`

Would need to determine the target repo and branch name somehow.

Straight forward close:
`git pull close <id>`

**Comment by kevinSuttle** [comment]
What about making `git request-pull` a 1st-class citizen on GitHub? http://git-scm.com/docs/git-request-pull

**Comment by AdrienGiboire** [comment]
It doesn't create pull requests. GitHub has its own Pull Request mechanism that we’ll go over in GitHub. `git request-pull` command generates an output you can email to the project maintainer manually. That's all.

Since last time, a lot happened regarding `octokit`. I'll try to go with [`Octokit/Client/PullRequests#create_pull_request`](http://www.rubydoc.info/gems/octokit/4.3.0/Octokit/Client/PullRequests#create_pull_request-instance_method) and [`Octokit/Client/PullRequests#update_pull_request`](http://www.rubydoc.info/gems/octokit/4.3.0/Octokit/Client/PullRequests#update_pull_request-instance_method).

**Comment by svnpenn** [comment]
For anyone not wanting to wait another 3 years, you can use

    hub pull-request

http://github.com/github/hub

**Comment by AdrienGiboire** [comment]
No need to be condescendant. For those who don't want to wait, they can contribute and even take over the project. That's what I did (mainly as a maintainer). You just need to ask.

Still, `hub` is a perfect alternative.

**Comment by ghost** [comment]
@AdrienGiboire a comment on why you are closing this without fixing would be appropriate

**Comment by whoshallsucceed** [comment]
As you rightly mentioned, this is going nowhere. The OP does not seem to be about to make the PR and I don't have time to duplicate behaviours implemented by hub.

**Comment by ghost** [comment]
So you close all issues that dont have a PR? Why have issues at all?

**Comment by whoshallsucceed** [comment]
Because this is a request for a feature, pending for a long time now. I don't handle bug issues the same way.
